Add language switcher, base project info
F1st3K/EasyVPN pull request #48
Opened 2024-08-19 20:20 UTC by sw1pr0g

2024-08-19 21:49 UTC, F1st3K requested changes
Its OK, please refactoring other readme files.

2024-08-21 07:47 UTC, sw1pr0g commented
@F1st3K please check changes. Main readme now have multilang support. Any ideas for additions and improvements in structure and content will be appreciated by me.

2024-08-21 21:09 UTC, F1st3K approved these changes

2024-08-21 21:09 UTC, F1st3K approved these changes

2025-04-13 20:16 UTC, closed without merging